### ISSUE TITLE
why is anytweaks crashing every time i go in a song?

### ISSUE THREAD

**Issue by Schpek5231** [ItsKaitlyn03/AnyTweaks#1]
i play on quest 2 and anytweaks keeps crashing every time i go into a song. how do i fix this?
(its not on bloom btw)

**Comment by alterseries83** [comment]
Same here on both Quest 1 and 2. I have disabled all the mods and uninstall all of them, except AnyTweaks. But it still crashes.

**Comment by jaskor** [comment]
Same for me. Game keeps crashing everytime I start a song. It stops when I disable AnyTweaks.

**Comment by whatdahopper** [comment]
There's a bug in AnyTweaks causing this to happen, I'll try fixing it when I have the chance to.

**Comment by KeithUntitled** [comment]
i have no problem

**Comment by cal117** [comment]
Currently working on a fix: #2

**Comment by cal117** [comment]
Its not AnyTweaks, its another mod.
