### ISSUE TITLE
Min FPS counter does not work properly

### ISSUE THREAD

**Issue by wilco375** [ItsKaitlyn03/AnyTweaks#5]
The minimum FPS counter always shows something like 2 FPS for me, even if the entire song runs at ~90 FPS. I suspect this is because in the first second or so it might still be loading some stuff of the map and thus have low FPS there? The min FPS counter isn't very useful like this. Maybe a slight delay can be added between the map loading and the mod saving the lowest FPS?

**Comment by whatdahopper** [comment]
Not my fault, blame Beat Games. Bug them about it since I just use their FPS counter, won't fix.
