### ISSUE TITLE
Version number seems wrong

### ISSUE THREAD

**Issue by Ancillius** [ItsKaitlyn03/AnyTweaks#7]
I downloaded the v6.1.1 for BS 1.27 qmod file from here and via https://computerelite.github.io/tools/Beat_Saber/questmods.html 

The ingame modlist shows 6.1.0 also the crash reporter https://analyzer.questmodding.com/crashes/s3sM states that.

BMBF showas 6.1.1 in the modlist. 

There seems to be some version mismatch in the code.

**Comment by whatdahopper** [comment]
It doesn't really matter, fixing this issue as-is isn't really worth the effort if it works fine anyways. Won't fix.
